// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBJgvttIcsuHlaHK618GFb4VmcevH5kHc',
    appId: '1:552787686868:web:c294e5934c3ba86835d241',
    messagingSenderId: '552787686868',
    projectId: 'finworh-task',
    authDomain: 'finworh-task.firebaseapp.com',
    storageBucket: 'finworh-task.firebasestorage.app',
    measurementId: 'G-VVGC8XJS13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiWaQS5tTq2JVDTN5kJK9YueBec_CFuiM',
    appId: '1:552787686868:android:ba30c5b725a98b0735d241',
    messagingSenderId: '552787686868',
    projectId: 'finworh-task',
    storageBucket: 'finworh-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDseeZJVQY4fW7X8vVTlIM-m2EJwdPfDQw',
    appId: '1:552787686868:ios:9c71e58c2a3caf8a35d241',
    messagingSenderId: '552787686868',
    projectId: 'finworh-task',
    storageBucket: 'finworh-task.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDseeZJVQY4fW7X8vVTlIM-m2EJwdPfDQw',
    appId: '1:552787686868:ios:9c71e58c2a3caf8a35d241',
    messagingSenderId: '552787686868',
    projectId: 'finworh-task',
    storageBucket: 'finworh-task.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBJgvttIcsuHlaHK618GFb4VmcevH5kHc',
    appId: '1:552787686868:web:d0bf24faeab6512735d241',
    messagingSenderId: '552787686868',
    projectId: 'finworh-task',
    authDomain: 'finworh-task.firebaseapp.com',
    storageBucket: 'finworh-task.firebasestorage.app',
    measurementId: 'G-6PM8VQ49JW',
  );
}
